### PR TITLE
Fix of typo

### PR DESCRIPTION
**Pull request by TomasRoj**

### CODE REVIEW

**Comment by mitzimarie** [comment]
Good day sir, I tried your code in AD9833 using Arduino Uno and I encountered this problem
Error: no matching function for call to ad9833::ad9833()

in AD9833_test.ino, can you please help me troubleshoot?

**Comment by TomasRoj** [comment]
Hi,

this pull request only fixes some misspelling which arent in the names of functions, methods or classes. Its problably problem on your side and this pull reqest can be merge.

**Comment by mitzimarie** [comment]
Thank you very much for the response sir. I already resolve the problem
sir, by the way sir I can ask the circuit diagram of the arduino uno to
ad9833?

**Comment by TomasRoj** [comment]
I have no idea, sorry. BTW if you make library you shoud know how to do it right? Please merge.

**Pull request merged**
